use_frameworks!

platform :ios, '12.0'

target 'zy_lib_become_ocr_ios_Example' do
  pod 'zy_lib_become_ocr_ios', :path => '../'
  pod 'BecomeSDK', :git => 'https://github.com/ZYTRUST/BecomeSDK.git', :tag => '1.1.0'

  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
           if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
           end
        end
    end
 end
