use_frameworks!

platform :ios, '12.0'

target 'zy_lib_become_ocr_ios_Example' do
  pod 'zy_lib_become_ocr_ios', :path => '../'
  pod 'BecomeDigitalV', :git => 'https://github.com/ZYTRUST/BecomeDigitalV.git', :tag => '2.0'
  pod 'Microblink', :git => 'https://github.com/ZYTRUST/Microblink.git', :tag => '1.1'
  #pod 'PPBlinkID', '5.20.0'

end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#           if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
#             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#           end
#        end
#    end
# end

